### ISSUE TITLE
FOUNDATIONS: Contributor `AddAsync`

### ISSUE THREAD

**Issue by glhays** [The-Standard-Organization/GitFyle.Core.Api#115]

**Comment by makhammadsoliyev** [comment]
I can grab this.

**Comment by glhays** [comment]
@pratikkaje you can take the Foundations for this entity if you like.

**Comment by pratikkaje** [comment]
@glhays I want to complete the controller for Configuration first. If this task is still available afterward, I will take it.

**Comment by glhays** [comment]
> @glhays I want to complete the controller for Configuration first. If this task is still available afterward, I will take it.

Sure, just create the appropriate Issue CONTROLLERS: Configuration Post Tests, one issue for each action.
