### ISSUE TITLE
DOCUMENTATION: Readme V2.10.3

### ISSUE THREAD

**Issue by glhays** [The-Standard-Organization/GitFyle.Core.Api#134]
Set badge to new version V2.10.3

**Comment by Lezune** [comment]
Waiting for "The Standard" to be updated to v2.10.3 before editing the badge.

**Comment by glhays** [comment]
> Waiting for "The Standard" to be updated to v2.10.3 before editing the badge.

Jacob, v2.10.3 is released now.... FYI

**Comment by Lezune** [comment]
> > Waiting for "The Standard" to be updated to v2.10.3 before editing the badge.
> 
> Jacob, v2.10.3 is released now.... FYI

Thank you for the heads up, Greg!
