### ISSUE TITLE
BROKERS: LoggingBroker - LogCritical

### ISSUE THREAD

**Issue by cjdutoit** [The-Standard-Organization/GitFyle.Core.Api#31]

**Comment by SlimAhmad** [comment]
@cjdutoit Remote: Permission to The-Standard-Organization/GitFyle.Core.Api.git denied to SlimAhmad.
Error encountered while pushing to the remote repository: Git failed with a fatal error.

**Comment by Lezune** [comment]
@SlimAhmad Did you forked the repository?

**Comment by SlimAhmad** [comment]
@Lezune  Thank you
