### ISSUE TITLE
DATA: Source - Add fluent configuration

### ISSUE THREAD

**Issue by cjdutoit** [The-Standard-Organization/GitFyle.Core.Api#39]
## Model: Source

Properties:

| Field                  | Type                  | Description                                                |
| --- | --- | --- |
| Id                     | Guid                  | Our internal identifier                                    |
| Name | string (Required, max 255) | The name of the source system e.g. GitHub / DevOps |
| Url | string (Required, max 255) | The name of the source system e.g. GitHub / DevOps |

** **_Extra considerations: Add a unique constraint on Name. This will ensure we do not have duplicate sources._**

**Comment by kandarpgautam** [comment]
I am picking this one as discussed.
