### ISSUE TITLE
DATA: Repository

### ISSUE THREAD

**Issue by cjdutoit** [The-Standard-Organization/GitFyle.Core.Api#4]
## Model:  Repository

| Field            | Type                   | Description                                                 |
| ---------------- | ---------------------- | ----------------------------------------------------------- |
| Id               | Guid                   | Our internal identifier                                      |
| Name             | string (Required, max 255) | The repository name                                           |
| Owner            | string (Required, max 255) | The name that represents the user or organization            |
| ExternalId       | string (Required, max 255) | The external unique identifier                                |
| SourceId           | Guid   | The Id of the source                 |
| IsOrganization   | bool                   | A flag that indicates if this is a user or organization       |
| IsPrivate        | bool                   | A flag that indicates if this is a private repository         |
| Token            | string                 | The token that should be used to access private repos         |
| TokenExpireAt      | DateTimeOffset         | When the token will expire                                    |
| Description     | string         | A description of the repo                                    |
| CreatedAt     | DateTimeOffset         | When the remote repo was created     |
| UpdatedAt     | DateTimeOffset         | When the remote repo was last updated    |

** **_Extra considerations:  Add a unique constraint on (ExternalId, Source).  This will ensure we do not have duplicate repositories._**

![image](https://github.com/The-Standard-Organization/GitFyle.Core.Api/assets/797750/732559ae-bec6-42fa-937f-56a817c5d8a5)

**Comment by AmineTissilguit** [comment]
I'm taking it :)
