### ISSUE TITLE
DATA: Contributor

### ISSUE THREAD

**Issue by cjdutoit** [The-Standard-Organization/GitFyle.Core.Api#5]
## Model: Contributor

Properties:
| Field       | Type                             | Description                                        |
|-------------|----------------------------------|----------------------------------------------------|
| Id          | Guid                           | Our internal identifier                            |
| ExternalId  | string (Required, max 255)     | The external unique identifier                     |
| SourceId      | Guid (Required)     | The source Id of the source     |
| Username    | string (Required, max 255)     | The username / login of the contributor            |
| Name        | string (Optional, max 255)     | The name of the contributor                        |
| Email       | string (Optional, max 255)     | The email address of the contributor               |
| AvatarUrl   | string (Optional)              | The avatar Url of the contributor                  |
| CreatedAt     | DateTimeOffset         | When the remote repo was created     |
| UpdatedAt     | DateTimeOffset         | When the remote repo was last updated    |

** **_Extra considerations: Add a unique constraint on (ExternalId, Source). This will ensure we do not have duplicate contributors for a source._**

![image](https://github.com/The-Standard-Organization/GitFyle.Core.Api/assets/797750/732559ae-bec6-42fa-937f-56a817c5d8a5)

**Comment by Lezune** [comment]
Mind if I snag this one?
