### ISSUE TITLE
DATA: Contribution

### ISSUE THREAD

**Issue by cjdutoit** [The-Standard-Organization/GitFyle.Core.Api#6]
## Model: Contribution

| Field                  | Type                  | Description                                                |
|------------------------|-----------------------|------------------------------------------------------------|
| Id                     | Guid                  | Our internal identifier                                    |
| RepositoryId           | Guid                  | Foreign key to Repository.Id                               |
| ContributorId          | Guid                  | Foreign key to Contributor.Id                              |
| ContributionTypeId     | Guid                  | Foreign key to ContributionType.Id                         |
| ExternalId             | string                | Required, max 255 characters                              |
| Title                  | string                | Required, max 255 characters                              |
| CreatedAt              | DateTimeOffset       | The date/time the contribution / pull request was created  |
| UpdatedAt              | DateTimeOffset       | The date/time the contribution / pull request was updated  |
| MergedAt               | DateTimeOffset       | The date/time the contribution / pull request was merged    |

** **_Extra considerations: Add a unique constraint on (RepositoryId , ExternalId). This will ensure we do not have duplicate contributions for a repository._**

![image](https://github.com/The-Standard-Organization/GitFyle.Core.Api/assets/797750/732559ae-bec6-42fa-937f-56a817c5d8a5)

**Comment by stagep** [comment]
As each contribution has the value tied to the ContributionType.Value, how does the size of a contribution become a factor in the overall value? I.e. if a PR involved a few lines of code versus 100 lines of code, would it be considered one contribution with the same value?

**Comment by cjdutoit** [comment]
@stagep we will assign a value for each type based on its effort/complexity.  When you are awarded that value / score it will be for the task being completed at that complexity level.   It will not take into account how many lines of code was written.

See https://gitfyle.com/about for the current value assignments.

**Comment by kandarpgautam** [comment]
can I pick this up?

**Comment by kandarpgautam** [comment]
For me to be able to reference other related types, we will need to get them merged.
