### ISSUE TITLE
DATA: ContributionType

### ISSUE THREAD

**Issue by cjdutoit** [The-Standard-Organization/GitFyle.Core.Api#7]
Model Name: ContributionType

Properties:

| Field                  | Type                  | Description                                                |
| --- | --- | --- |
| Id                     | Guid                  | Our internal identifier                                    |
| Name | string (Required, max 255) | The name of the contribution type e.g. BROKERS / FOUNDATIONS |
| Value | int (Required) | The value that we want to assign for the effort involved for this contribution type |

** **_Extra considerations: Add a unique constraint on Name. This will ensure we do not have duplicate types._**

![image](https://github.com/The-Standard-Organization/GitFyle.Core.Api/assets/797750/d21306e2-f46a-4ea6-b0f9-ad437e67659b)

**Comment by kandarpgautam** [comment]
This issue has not been assigned to anyone yet. can I pick this up even if no one's assigned?
