### ISSUE TITLE
INFRA: Set HTTP Uses HomeController

### ISSUE THREAD

**Issue by glhays** [The-Standard-Organization/GitFyle.Core.Api#75]
Easy first pr for someone.
We need to set the new .Net8 Http file to use our HomeController as the base for the api.

![image](https://github.com/The-Standard-Organization/GitFyle.Core.Api/assets/42452283/302bd8c2-a086-4bc0-825f-d1cca2c2e7dd)

![image](https://github.com/The-Standard-Organization/GitFyle.Core.Api/assets/42452283/62ef2262-43cb-4619-b092-e617b3ad058e)

**Comment by makhammadsoliyev** [comment]
I am picking this one
